/**
 * @author Benjamin Guirlet
 * @file
 *      This file contains the 'memes_channel' command.
 *      This command allows the server administrators to define in which channels memes will be treated.
 */


const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction } = require( "discord.js" );


/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
	.setName( "salon_memes" )
	.setDescription( "Permet de d'ajouter ou enlever le salon courant comme un salon de memes pour le bot." )
	.addSubcommand( subCommand =>
		subCommand
			.setName( "add" )
			.setDescription( "Ajoute le salon actuel comme salon de memes." )
	)
	.addSubcommand( subCommand =>
		subCommand
			.setName( "remove" )
			.setDescription( "Enlève le salon courant comme salon de memes." )
	);


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * Function called when the command 'salon_memes'
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
async function execute( interaction ) {
	switch ( interaction.options.getSubcommand() ) {
		case 'add':
			break;
		case 'remove':
			break;
	}
}

/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	execute
}