/**
 * @author Benjamin Guirlet
 * @description
 *      This file contains the command 'clear_channels'.
 *      This command removes all the unused channels from the database.
 *      It is administrator only.
 */


const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction } = require( "discord.js" );
const sqlUtils = require( "../../utils/sqlUtils" );
const { ADMINS } = require( "../../files/config.json" );


/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
	.setName( "clear_channels" )
	.setDescription( "Supprime tout les salons inutilisés de la table Channels." );


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * Function called when the command 'feed'
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
async function execute( interaction ) {
	if ( !ADMINS.includes( interaction.user.id ) ) {
		await interaction.reply(
			{ content: "Vous n'avez pas les permissions pour exécuter cette commande.", ephemeral: true }
		);
		return;
	}

	await sqlUtils.query(
		"DELETE FROM Channels WHERE memes=false AND repost=false AND feed=false AND logs=false AND stats=false;"
	);

	await interaction.reply(
		{ content: "Tout les salons inutilisés ont été supprimés de la base de données!", ephemeral: true }
	);
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	execute
}