/**
 * @author Benjamin Guirlet
 * @description
 *      Contains the command 'logs'.
 *      It allows the administrators to define in which channel the logs feature is enabled.
 */


const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction } = require( "discord.js" );
const sqlUtils = require( "../../utils/sqlUtils" );


/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
	.setName( "logs" )
	.setDescription( "Permet de définir ou désactiver le salon des logs pour le bot." )
	.setDefaultPermission( false )
	.addSubcommand( subCommand =>
		subCommand
			.setName( "set" )
			.setDescription( "Défini le salon courant comme le salon des logs." )
	)
	.addSubcommand( subCommand =>
		subCommand
			.setName( "remove" )
			.setDescription( "Désactive le salon des logs." )
	);


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * Function called when the command 'logs'
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
async function execute( interaction ) {
	let logsChannel;
	switch ( interaction.options.getSubcommand() ) {
		case 'set':
			// We're removing the precedent feed channel if there is one because there can be only one at the same time.
			logsChannel = await sqlUtils.fetchChannelsByType( "logs" );
			if ( logsChannel.length )
				await sqlUtils.updateChannel( logsChannel[0].channel_id, "logs", false )

			await sqlUtils.updateChannel( interaction.channelId, "logs", true );
			await interaction.reply(
				{ content: "Ce salon est maintenant le salon des logs!", ephemeral: true }
			);
			break;
		case 'remove':
			logsChannel = await sqlUtils.fetchChannelsByType( "logs" );

			if ( logsChannel.length ) {
				await sqlUtils.updateChannel( logsChannel[0].channel_id, "logs", false );
				await interaction.reply(
					{ content: "Le salon des logs a été désactivé!", ephemeral: true }
				);
				break;
			}
			await interaction.reply(
				{ content: "Il n'y a pas de salon des logs déjà défini!", ephemeral: true }
			);
	}
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	adminsOnly: true,
	data: slashCommand,
	execute
}