/**
 * @author Benjamin Guirlet
 * @file
 *		Display the information about the average.
 */


const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction, MessageEmbed } = require( "discord.js" );
const sqlUtils = require( "../../utils/sqlUtils" );


/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
	.setName( "moyenne" )
	.setDescription( "Affiche des informations sur la moyenne." );


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * Handler for this slashCommand command.
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
async function execute( interaction ) {
	const averageData = (await sqlUtils.query( "SELECT * FROM Average" ))[0];
	await interaction.reply({
		embeds: [
			new MessageEmbed()
				.addField( "Moyenne actuelle", `${averageData["average"]}` )
				.addField( "Nombre de memes dans le calcul de la moyenne", `${averageData["nb_msg_average"]}` )
	]});
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	execute
}