/**
 * @author Benjamin Guirlet
 * @file
 *      This file contains the 'memes_channel' command.
 *      This command allows the server administrators to define in which channels memes will be treated.
 */


const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction } = require( "discord.js" );
const sqlUtils = require( "../../utils/sqlUtils" );
const { ADMINS } = require( "../../files/guild_data.json" );


/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
	.setName( "salon_memes" )
	.setDescription( "Permet de d'ajouter ou enlever le salon courant comme un salon de memes pour le bot." )
	.addSubcommand( subCommand =>
		subCommand
			.setName( "add" )
			.setDescription( "Ajoute le salon actuel comme salon de memes." )
	)
	.addSubcommand( subCommand =>
		subCommand
			.setName( "remove" )
			.setDescription( "Enlève le salon courant comme salon de memes." )
	);


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * Function called when the command 'salon_memes'
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
async function execute( interaction ) {
	if ( !ADMINS.includes( interaction.user.id ) ) {
		await interaction.reply(
			{ content: "Vous n'avez pas les permissions pour exécuter cette commande.", ephemeral: true }
		);
		return;
	}

	switch ( interaction.options.getSubcommand() ) {
		case 'add':
			await addMemeChannel( interaction, interaction.channelId );
			break;
		case 'remove':
			break;
	}
}


/**
 * @param {CommandInteraction} interaction
 * @param {string} channelID
 */
async function addMemeChannel( interaction, channelID ) {
	const channel = await sqlUtils.getChannel( channelID );

	// Checking the array's length to know is the channel is already in the database.
	if ( !channel.length )
		await sqlUtils.addChannel( channelID );
	await sqlUtils.updateChannel( channelID, "memes", true );

	await interaction.reply(
		{ content: "Ce salon est maintenant un salon de memes!", ephemeral: true }
	);
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	execute
}