/**
 * @author Benjamin Guirlet
 * @description
 *      This file contains the 'set' command.
 *      It allows the server administrators to define which functionnalities will be activated on a channel.
 */


const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction, MessageEmbed } = require( "discord.js" );
const sqlUtils = require( "../../utils/sqlUtils" );


/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
	.setName( "set" )
	.setDescription( "Permet d'activer/désactiver des fonctionnalités sur un salon." )
	.setDefaultPermission( false )
	.addBooleanOption( option =>
		option
			.setName( "memes" )
			.setDescription( "Activation/désactivation d'un salon de memes." )
	)
	.addBooleanOption( option =>
		option
			.setName( "reposts" )
			.setDescription( "Activation/désactivation d'un salon de reposts." )
	)
	.addBooleanOption( option =>
		option
			.setName( "threads" )
			.setDescription( "Activation/désactivation des threads dans un salon (bloque les messages)." )
	)
	.addBooleanOption( option =>
		option
			.setName( "feed" )
			.setDescription( "Activation/désactivation du salon du feed." )
	)
	.addBooleanOption( option =>
		option
			.setName( "stats" )
			.setDescription( "Activation/désactivation du salon des stats mensuelles." )
	)
	.addBooleanOption( option =>
		option
			.setName( "logs" )
			.setDescription( "Activation/désactivation du salon des logs." )
	)
	.addBooleanOption( option =>
		option
			.setName( "all" )
			.setDescription( "Désactive/active toutes les fonctionnalités du salon." )
	);


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * Function called when the command 'set'
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
async function execute( interaction ) {
	// When no arguments are passed to the command, then we activate all functionnalities on the channel.
	const options = interaction.options;
	if ( options.data.length === 0 ) {
		await changeAllValues( interaction.channelId, true );
	}
	else {
		if ( options.get ( "memes" ) )
			await sqlUtils.updateChannel( interaction.channelId, "memes", options.get( "memes" ).value );
		if ( options.get ( "reposts" ) )
			await sqlUtils.updateChannel( interaction.channelId, "reposts", options.get( "reposts" ).value );
		if ( options.get ( "threads" ) )
			await sqlUtils.updateChannel( interaction.channelId, "threads", options.get( "threads" ).value );
		if ( options.get ( "feed" ) )
			await sqlUtils.updateChannel( interaction.channelId, "feed", options.get( "feed" ).value );
		if ( options.get ( "logs" ) )
			await sqlUtils.updateChannel( interaction.channelId, "logs", options.get( "logs" ).value );
		if ( options.get ( "stats" ) )
			await sqlUtils.updateChannel( interaction.channelId, "stats", options.get( "stats" ).value );
		if ( options.get( "all" ) )
			await changeAllValues( interaction.channelId, options.get( "all" ).value );
	}

	const channel = await sqlUtils.fetchChannel( interaction.channelId );
	const embed = new MessageEmbed()
		.setDescription( `**Memes :** ${channel.memes}\n**Reposts :** ${channel.reposts}\n**Threads :** ` +
			`${channel.threads}\n**Feed :** ${channel.feed}\n**Logs :** ${channel.logs}\n**Stats :** ${channel.stats}` )
		.setAuthor( "| Fonctionnalités du salon", interaction.user.avatarURL() );


	await interaction.reply( { embeds: [ embed ], ephemeral: true } );
}


/**
 * Change all the values of a channel to the specified channel.
 * @param {string} channelId The channel discord ID.
 * @param {boolean} value The new value of the channel's functionnalities.
 */
async function changeAllValues( channelId, value ) {
	await sqlUtils.updateChannel( channelId, "reposts", value );
	await sqlUtils.updateChannel( channelId, "memes", value );
	await sqlUtils.updateChannel( channelId, "threads", value );
	await sqlUtils.updateChannel( channelId, "feed", value );
	await sqlUtils.updateChannel( channelId, "logs", value );
	await sqlUtils.updateChannel( channelId, "stats", value );
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	adminsOnly: true,
	data: slashCommand,
	execute
}